---

name: Reverse Dependencies
run-name: Reverse Dependencies (test)
on:
  workflow_dispatch:

jobs:

      
  bayesplot-revdeps:
    uses: andrjohns/ci-scripts/.github/workflows/revdeps.yml@revdeps
    with:
      package: bayesplot
      bayesplot-source: master

