---

name: Reverse Dependencies
run-name: Reverse Dependencies (test)
on:
  workflow_dispatch:

jobs: 
  rstan-revdeps:
    uses: andrjohns/ci-scripts/.github/workflows/revdeps.yml@revdeps
    with:
      package: rstan
      rstan-source: v2.39.0
      
